#!/bin/sh
sudo mv ./scrollbars.css /Applications/Firefox.app/content/resources
sudo sh -c 'echo "override chrome://global/skin/scrollbars.css scrollbars.css" > /Applications/Firefox.app/content/resources/chrome.manifest'
